### ISSUE TITLE
Request permissions button is grayed out

### ISSUE THREAD

**Issue by purejava** [silentsakky/zarafa-webapp-notifications#6]
Hi,

nice plugin!

I installed zarafa-webapp-desktopnotifications_1.0.31-28.2_all on latest Zarafa 7.2.3.657/WebApp 2.2.0.414-185.1 and read your [zarafa community post](https://community.zarafa.com/pg/plugins/project/22240/developer/silentsakky/webapp-desktop-notifications) as well. The web server has read permissions:

```
root@box:/usr/share/zarafa-webapp/plugins# ls -l
total 4
drwxr-xr-x 5 root root 4096 Mai 12 10:01 desktopnotifications
root@box:/usr/share/zarafa-webapp/plugins# 
```

It's not possible to activate the notifications, as the button is grayed out.
![not](https://cloud.githubusercontent.com/assets/1822238/15208387/870c7c06-182b-11e6-8b1f-a3c84bc4bf05.png)
Tested it on lastest Chomium and FF (both 64bit) on Arch linux.

Thanks.

**Comment by silentsakky** [comment]
Request permission button will only be enabled if webapp don't have rights
to show notifications, if it has then it will be greyed out.

On Thu, May 12, 2016 at 1:53 PM, Ralph Plawetzki notifications@github.com
wrote:

> Hi,
> 
> nice plugin!
> 
> I installed zarafa-webapp-desktopnotifications_1.0.31-28.2_all on latest
> Zarafa 7.2.3.657/WebApp 2.2.0.414-185.1 and read your zarafa community
> post
> https://community.zarafa.com/pg/plugins/project/22240/developer/silentsakky/webapp-desktop-notifications
> as well. The web server has read permissions:
> 
> root@box:/usr/share/zarafa-webapp/plugins# ls -l
> total 4
> drwxr-xr-x 5 root root 4096 Mai 12 10:01 desktopnotifications
> root@box:/usr/share/zarafa-webapp/plugins#
> 
> It's not possible to activate the notifications, as the button is grayed
> out.
> [image: not]
> https://cloud.githubusercontent.com/assets/1822238/15208387/870c7c06-182b-11e6-8b1f-a3c84bc4bf05.png
> Tested it on lastest Chomium and FF (both 64bit) on Arch linux.
> 
> Thanks.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/silentsakky/zarafa-webapp-notifications/issues/6

## 

My Email Addresses:-
      s s.patel@zarafa.comaket.d.patel@gmail.com
      saket.patel@yahoo.com

**Comment by purejava** [comment]
Ok, with a fresh installation of the browser the button was not greyed out, the permissions could be set and notifications are working now.

Thanks. Closing this issue.
